// Core types shared across the kit.
//
// Naming note: Tradingale's API serves DIMENSIONLESS model parameters only
// (no prices, no quantities, no amounts). The user supplies the budget, the
// market supplies the entry price, `computeLadder` derives everything else.

/** Model parameters as served by the Tradingale API / MCP for one instrument. */
export interface SequenceParams {
  /** Price spacing between levels, as a fraction (e.g. 0.08 = 8%). */
  deltaPrice: number;
  /** Number of levels in the structure (4 or 5). */
  nbRounds: number;
  /**
   * Level-to-level QUANTITY ratios (length nbRounds - 1).
   * ⚠ Multipliers scale token QUANTITIES, never dollar costs:
   *   qty[n] = qty[n-1] * multipliers[n-2]
   * Applying them to bet amounts is the classic integration bug.
   */
  multipliers: number[];
  /** Fraction of the budget spent on level 1 (dimensionless). */
  initialBetRatio: number;
  /** Descriptive metrics (0..5). Informational only, never a recommendation. */
  martingaleScore?: number;
  startingale?: number;
  symbol?: string;
}

/** Per-asset order grids as declared by a venue. */
export interface VenueGrids {
  /** Price tick (e.g. Binance PRICE_FILTER.tickSize). Null = not declared. */
  priceIncrement: number | null;
  /** Quantity step (e.g. LOT_SIZE.stepSize, Alpaca min_trade_increment). */
  qtyStep: number | null;
  /** Minimum order size in base units (e.g. 0.0001 BTC). */
  minOrderSize: number | null;
  /** Minimum order value in quote units (e.g. Binance MIN_NOTIONAL). */
  minNotional: number | null;
}

/** One level of a computed ladder. */
export interface LadderLevel {
  /** 1-based level number; level 1 is the market entry. */
  level: number;
  /** Buy price for this level (level 1: entry price). */
  buyPrice: number;
  /** Quantity bought at this level, in base units. */
  quantity: number;
  /** Cost of this level in quote units (quantity * buyPrice). */
  cost: number;
  /** Cumulative quantity held once this level fills. */
  cumulativeQuantity: number;
  /** Exit (sell) price if this is the deepest filled level. */
  exitPrice: number;
}

export interface Ladder {
  levels: LadderLevel[];
  totalCost: number;
  budget: number;
  entryPrice: number;
  params: SequenceParams;
  /** True when quantities/prices were snapped to venue grids. */
  snapped: boolean;
}

export type OrderSide = 'buy' | 'sell';
export type OrderType = 'market' | 'limit';
export type OrderStatus = 'open' | 'filled' | 'canceled' | 'expired' | 'rejected';

/** An order as the ENGINE sees it (venue-agnostic). */
export interface PlannedOrder {
  /** Stable id generated by the plan; venues echo it as client order id. */
  clientId: string;
  side: OrderSide;
  type: OrderType;
  /** Limit price (absent for market orders). */
  price?: number;
  quantity: number;
  /** Level this order belongs to (sell orders: the level they exit). */
  level: number;
}

export interface VenueOrder {
  clientId: string;
  side: OrderSide;
  status: OrderStatus;
  price?: number;
  quantity: number;
  filledQuantity: number;
}

export interface Fill {
  clientId: string;
  side: OrderSide;
  price: number;
  quantity: number;
  timestamp: number;
}
